language:
  - python

env:
  global:
    - WINDOWS=0
    - SITECUSTOMIZELIBPATH=0
    - PYPY=0

dist: trusty
matrix:
  include:
    - os: linux
      # BUILD 1 -------------------
      python: 3.6
      env: WINDOWS=1
    - os: linux
      # BUILD 2 -------------------
      python: 2.7
      env:
        # gcc 4.8.4 with c++98
        - XML_GENERATOR="castxml"
        - SITECUSTOMIZELIBPATH="/home/travis/virtualenv/python2.7/lib/python2.7/sitecustomize.py"
    - os: linux
      # BUILD 3 -------------------
      python: 3.4
      env:
        # gcc 4.8.4 with c++98
        - XML_GENERATOR="castxml"
        - SITECUSTOMIZELIBPATH="/home/travis/virtualenv/python3.4/lib/python3.4/sitecustomize.py"
    - os: linux
      # BUILD 4 -------------------
      python: 3.5
      env:
        # gcc 4.8.4 with c++98
        - XML_GENERATOR="castxml"
        - SITECUSTOMIZELIBPATH="/home/travis/virtualenv/python3.5/lib/python3.5/sitecustomize.py"
    - os: linux
      # BUILD 5 -------------------
      python: 3.6
      env:
        # gcc 4.8.4 with c++98
        - XML_GENERATOR="castxml"
        - SITECUSTOMIZELIBPATH="/home/travis/virtualenv/python3.6/lib/python3.6/sitecustomize.py"
    - os: linux
      # BUILD 6 -------------------
      python: pypy
      env:
        # gcc 4.8.4 with c++98
        - XML_GENERATOR="castxml"
        - SITECUSTOMIZELIBPATH="/home/travis/virtualenv/pypy/lib-python/2.7/sitecustomize.py"
        - PYPY=1
    - os: linux
      # BUILD 7 -------------------
      python: pypy3
      env:
        # gcc 4.8.4 with c++98
        - XML_GENERATOR="castxml"
        - SITECUSTOMIZELIBPATH="/home/travis/virtualenv/pypy3/lib-python/3/sitecustomize.py"
        - PYPY=1
    - os: linux
      # BUILD 8 -------------------
      python: 3.6
      env:
        # gcc 5.4.1 with c++98
        - XML_GENERATOR="castxml"
        - COMPILER=g++-5
        - SITECUSTOMIZELIBPATH="/home/travis/virtualenv/python3.6/lib/python3.6/sitecustomize.py"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
    - os: linux
      # BUILD 9 ------------------
      python: 3.6
      env:
        - XML_GENERATOR="castxml"
        - SITECUSTOMIZELIBPATH="/home/travis/virtualenv/python3.6/lib/python3.6/sitecustomize.py"
    - os: linux
      # BUILD 10 ------------------
      python: 3.6
      env:
        # gcc 4.8.4 with c++03
        - XML_GENERATOR="castxml"
        - CPPSTD="-std=c++03"
        - SITECUSTOMIZELIBPATH="/home/travis/virtualenv/python3.6/lib/python3.6/sitecustomize.py"
    - os: linux
      # BUILD 11 ------------------
      python: 3.6
      env:
        # gcc 4.8.4 with c++11
        - XML_GENERATOR="castxml"
        - CPPSTD="-std=c++11"
        - SITECUSTOMIZELIBPATH="/home/travis/virtualenv/python3.6/lib/python3.6/sitecustomize.py"
    - os: linux
      # BUILD 12 ------------------
      python: 3.6
      env:
        # gcc 5.4.1 with c++11
        - XML_GENERATOR="castxml"
        - COMPILER=g++-5
        - CPPSTD="-std=c++11"
        - SITECUSTOMIZELIBPATH="/home/travis/virtualenv/python3.6/lib/python3.6/sitecustomize.py"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
    - os: linux
      # BUILD 13 ------------------
      python: 3.6
      env:
        # gcc 5.4.1 with c++14
        - XML_GENERATOR="castxml"
        - COMPILER=g++-5
        - CPPSTD="-std=c++14"
        - SITECUSTOMIZELIBPATH="/home/travis/virtualenv/python3.6/lib/python3.6/sitecustomize.py"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
    - os: osx
      # BUILD 14 ------------------
      osx_image: xcode11.2
      language: generic
      env:
        - XML_GENERATOR="castxml"
        - TRAVIS_PYTHON_VERSION="2"
        - SITECUSTOMIZELIBPATH="/usr/local/lib/python2.7/site-packages/sitecustomize.py"
    - os: osx
      # BUILD 15 ------------------
      osx_image: xcode11.2
      language: generic
      env:
        - XML_GENERATOR="castxml"
        - TRAVIS_PYTHON_VERSION="3"
        - SITECUSTOMIZELIBPATH="/usr/local/lib/python3.7/site-packages/sitecustomize.py"
    - os: linux
      # BUILD 16 ------------------
      python: 3.6
      env:
        - XML_GENERATOR="castxml-18032017"
        - SITECUSTOMIZELIBPATH="/home/travis/virtualenv/python3.6/lib/python3.6/sitecustomize.py"
    - os: linux
      # BUILD 17 ------------------
      python: 3.6
      env:
        - XML_GENERATOR="castxml-18032017"
        - CASTXML_EPIC="1"
        - SITECUSTOMIZELIBPATH="/home/travis/virtualenv/python3.6/lib/python3.6/sitecustomize.py"


before_install:
  # OS X
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then travis_retry brew update && brew upgrade; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ $TRAVIS_PYTHON_VERSION == 2 ]]; then brew install python@2; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ $TRAVIS_PYTHON_VERSION == 3 ]]; then brew install python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ $TRAVIS_PYTHON_VERSION == 3 ]]; then sudo ln -sf /usr/local/bin/pip3 /usr/local/bin/pip; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ $TRAVIS_PYTHON_VERSION == 3 ]]; then sudo ln -sf /usr/local/bin/python3 /usr/local/bin/python; fi

  # Download castxml binaries
  # To update the URLs, get the full URLS from ITK, and the run wget with --verbose on the URL.
  # Look at the redirection and extract the direct URL for usage with Travis.
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      if [ ! -e ${HOME}/castxml ]; then
        wget -q -O - https://data.kitware.com/api/v1/file/hashsum/sha512/88c9b5954ca7417f7b519f3006dc6fe4bd194af0837168edc30007a41eaae6d4eee97cef2a72747432af14941c7f60333b77c25e208b2540dcde2d61e0d0e6f3/download | tar zxf - -C ${HOME};
      fi;
    fi

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ $XML_GENERATOR == "castxml" ]]; then
      if [ ! -e ${HOME}/castxml ]; then
        wget -q -O - https://data.kitware.com/api/v1/file/hashsum/sha512/f43ef30267c850872cf1e8ea8594c5dc6a1beb7c343d63875662ee7c648dac4f9214c915499ef2e1148f2b5f866e4c518ca1a21fb5055baba7d62f4f69097ba0/download | tar zxf - -C ${HOME};
      fi;
    fi

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ $XML_GENERATOR == "castxml-18032017" ]]; then
      if [ ! -e ${HOME}/castxml ]; then
        wget -q -O - https://sourceforge.net/projects/pygccxml-castxml-binaries/files/castxml-linux-18032017.tar.gz | tar zxf - -C ${HOME};
      fi;
    fi

  # Add the castxml binary to the path
  - if [[ $XML_GENERATOR == "castxml" ]] || [[ $XML_GENERATOR == "castxml-18032017" ]]; then
      export PATH=$PATH:~/castxml/bin/;
    fi

  - if [[ $CPPSTD == "-std=c++03" ]]; then
      mv unittests/configs/travis_std03.cfg unittests/xml_generator.cfg;
    fi

  - if [[ $CPPSTD == "-std=c++11" ]]; then
      mv unittests/configs/travis_std11.cfg unittests/xml_generator.cfg;
    fi

  - if [[ $CPPSTD == "-std=c++14" ]]; then
      mv unittests/configs/travis_std14.cfg unittests/xml_generator.cfg;
    fi

  - if [[ "$COMPILER" == "g++-5" ]] && [[ $XML_GENERATOR == "castxml" ]]; then
     mv unittests/configs/travis_gcc5.cfg unittests/xml_generator.cfg;
    fi

  - if [[ $CASTXML_EPIC == "1" ]]; then
      mv unittests/configs/castxml_epic1.cfg unittests/xml_generator.cfg;
    fi

  - pip install coveralls
  - if [[ $WINDOWS == 0 ]]; then pip install coverage; fi

  # appveyor-artifacts will be used to fetch coverage results from appveyor
  - if [ $WINDOWS == 0 ]; then
      pip install pycodestyle;
    else
      pip install https://github.com/Robpol86/appveyor-artifacts/archive/master.zip;
    fi


script:
  - echo $TRAVIS_OS_NAME
  - echo $WINDOWS
  - python --version
  - c++ --version

  # Modify sitecustomize.py file for coverage. Allows to cover files run in a subprocess.
  - if [ $WINDOWS == 0 ]; then
      touch ${SITECUSTOMIZELIBPATH} || travis_terminate 1;
      printf "import coverage\ncoverage.process_startup()\n" > ${SITECUSTOMIZELIBPATH} || travis_terminate 1;
    fi

  # Install pygccxml, run the tests with coverage and
  # combine multiple .coverage files
  # We have multiple coverage files because some scripts run in a subprocess
  - if [[ $WINDOWS == 0 ]] && [[ $PYPY == 0 ]]; then
      python setup.py install || travis_terminate 1;
      coverage run -m unittests.test_all || travis_terminate 1;
      coverage combine || travis_terminate 1;
    fi
    # For pypy, do not run coverage, as this is extremely slow
    # https://bitbucket.org/pypy/pypy/issues/1871/10x-slower-than-cpython-under-coverage
    # This is fixed with pypy 4.0, which is not the pypy provided by Travis ...
  - if [[ $WINDOWS == 0 ]] && [[ $PYPY != 0 ]]; then
      python setup.py install || travis_terminate 1;
      python -m unittests.test_all || travis_terminate 1;
    fi
  # For the "empty" windows build, fetch the coverage results from appveyor
  - if [ $WINDOWS == 1 ]; then
      appveyor-artifacts -m --owner-name=iMichka --verbose download || travis_terminate 1;
    fi

after_success:
  # Send coverage result to https://coveralls.io/r/gccxml/pygccxml
  - coveralls
